coverage:
  range: 95..100
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 3%
        if_ci_failed: success #success, failure, error, ignore
